#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-new"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "1b481f2973a24329905197c5b498ad9f" }
]

[assets]
directory = "./public"
